export const GET_DISCUSSIONS = 'GET_DISCUSSIONS';
export const GET_DISCUSSION = 'GET_DISCUSSION';
export const POST_DISCUSSION = 'POST_DISCUSSION';
export const UPDATE_DISCUSSION = 'UPDATE_DISCUSSION';
export const LIKE_DISCUSSION = 'LIKE_DISCUSSION';
export const POST_REPLY = 'POST_REPLY';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
